---
# brew playbook

# - include: install_homebrew.yml

- name: "update Homebrew"
  homebrew: update_homebrew=yes

- name: "Tap Homebrew repos"
  homebrew_tap: name={{item}} state=present
  with_items: osx.taps

- name: "update Homebrew"
  homebrew: update_homebrew=yes

- name: "Install Homebrew packages"
  homebrew: name={{item.package}} install_options={{item.options | default("") }} state=latest
  with_items: osx.packages

- name: "Install Casks"
  homebrew_cask: name={{item}} state=installed
  environment:
    HOMEBREW_CASK_OPTS: "--force --appdir=/Applications"
  with_items: osx.casks
